# Configuration for Alacritty
draw_bold_text_with_bright_colors: true

font:
  size: 12.0

window:
  column: 80
  lines: 24
  decorations: 'full'

colors:
  primary:
   background: '#121212'
   foreground: '#e4e4e4'

  cursor:
    text: CellBackground
    cursor: '#ffffff'

  hints:
    start:
      background: '#ff8800'
      foreground: '#000000'
    end:
      background: '#ffff00'
      foreground: '#000000'

  normal:
    black:   '#262626'
    red:     '#d75f00'
    green:   '#5faf5f'
    yellow:  '#af8700'
    blue:    '#0087d7'
    magenta: '#875fff'
    cyan:    '#0087af'
    white:   '#b2b2b2'

  bright:
    black:   '#4e4e4e'
    red:     '#d7875f'
    green:   '#5fd75f'
    yellow:  '#d7af00'
    blue:    '#00afd7'
    magenta: '#af5fff'
    cyan:    '#00afaf'
    white:   '#e4e4e4'
