# Configuration for Alacritty, the GPU enhanced terminal emulator.

font:
  size: 12.0

colors:
  primary:
   background: '#1c1c1c'
   foreground: '#e4e4e4'

  cursor:
    text: CellBackground
    cursor: '#e4e4e4'

  hints:
    start:
      background: '#d7af00'
    end:
      foreground: '#d7af00'

  normal:
    black:   '#262626'
    red:     '#d75f00'
    green:   '#5faf5f'
    yellow:  '#af8700'
    blue:    '#0087d7'
    magenta: '#875fff'
    cyan:    '#0087af'
    white:   '#b2b2b2'

  bright:
    black:   '#4e4e4e'
    red:     '#d7875f'
    green:   '#5fd75f'
    yellow:  '#d7af00'
    blue:    '#00afd7'
    magenta: '#af5fff'
    cyan:    '#00afaf'
    white:   '#e4e4e4'
